### ISSUE TITLE
Contributor permissions to this repository

### ISSUE THREAD

**Issue by rich7409** [odomlab/osqpipe#1]
Hi Tim & Margus.

I hope you're both enjoying your new jobs. We've had some changes come up that means we need to make changes to this project, however I'm not able to do so. Would you mind adding my GitHub account to the odomlab group or these osq* projects please? I'm rich7409 on GitHub. My email is the same as always of course. I can add Gord once I'm in.

Thanks,
Rich.

**Comment by tfrayner** [comment]
Hi Rich,

No problem at all, I've added you as an owner of the Odom Lab group. Hoping CRUK-CI is still going strong.

Tim

**Comment by rich7409** [comment]
Hi. Thanks, looks like that has worked. I'll add Gord when he's back in.

Yes, all as it ever has been here really. This transfer to EBI has been a low key headache for quite a while that I've just been avoiding until today.

Rich.
